# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clansite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=20000)),
                ('published', models.BooleanField(default=True)),
                ('public_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-public_date'],
            },
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clansite.Category', verbose_name='category'),
        ),
    ]
